# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Write the gene sets list into fileName file, each line has as a first element the gene set id and then gene ids of the gene set
#' @param geneSetsRcpp list that has a gene set in every elemnt
#' @param fileName output file name
#' @pre fileName is not a null string
#' @post Gene sets written into fileName file
writeGeneSets <- function(geneSetsRcpp, fileName) {
    invisible(.Call(`_gseacc_writeGeneSets`, geneSetsRcpp, fileName))
}

readGeneSets <- function(fileName) {
    .Call(`_gseacc_readGeneSets`, fileName)
}

readCsv <- function(fileName, sep = ',', hasRowNames = TRUE, hasColNames = TRUE) {
    .Call(`_gseacc_readCsv`, fileName, sep, hasRowNames, hasColNames)
}

